package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends Model<M> implements IBean {

	public void setGysbh(java.lang.String gysbh) {
		set("GYSBH", gysbh);
	}

	public java.lang.String getGysbh() {
		return get("GYSBH");
	}

	public void setShxydm(java.lang.String shxydm) {
		set("SHXYDM", shxydm);
	}

	public java.lang.String getShxydm() {
		return get("SHXYDM");
	}

	public void setYyzzzch(java.lang.String yyzzzch) {
		set("YYZZZCH", yyzzzch);
	}

	public java.lang.String getYyzzzch() {
		return get("YYZZZCH");
	}

	public void setQymc(java.lang.String qymc) {
		set("QYMC", qymc);
	}

	public java.lang.String getQymc() {
		return get("QYMC");
	}

	public void setFddbr(java.lang.String fddbr) {
		set("FDDBR", fddbr);
	}

	public java.lang.String getFddbr() {
		return get("FDDBR");
	}

	public void setFddbrdh(java.lang.String fddbrdh) {
		set("FDDBRDH", fddbrdh);
	}

	public java.lang.String getFddbrdh() {
		return get("FDDBRDH");
	}

	public void setSss(java.lang.String sss) {
		set("SSS", sss);
	}

	public java.lang.String getSss() {
		return get("SSS");
	}

	public void setSss1(java.lang.String sss1) {
		set("SSS1", sss1);
	}

	public java.lang.String getSss1() {
		return get("SSS1");
	}

	public void setZs(java.lang.String zs) {
		set("ZS", zs);
	}

	public java.lang.String getZs() {
		return get("ZS");
	}

	public void setZczb(java.lang.String zczb) {
		set("ZCZB", zczb);
	}

	public java.lang.String getZczb() {
		return get("ZCZB");
	}

	public void setClrq(java.lang.String clrq) {
		set("CLRQ", clrq);
	}

	public java.lang.String getClrq() {
		return get("CLRQ");
	}

	public void setYyqx(java.lang.String yyqx) {
		set("YYQX", yyqx);
	}

	public java.lang.String getYyqx() {
		return get("YYQX");
	}

	public void setQylx(java.lang.String qylx) {
		set("QYLX", qylx);
	}

	public java.lang.String getQylx() {
		return get("QYLX");
	}

	public void setZzjgdm(java.lang.String zzjgdm) {
		set("ZZJGDM", zzjgdm);
	}

	public java.lang.String getZzjgdm() {
		return get("ZZJGDM");
	}

	public void setSwdjh(java.lang.String swdjh) {
		set("SWDJH", swdjh);
	}

	public java.lang.String getSwdjh() {
		return get("SWDJH");
	}

	public void setYxq(java.lang.String yxq) {
		set("YXQ", yxq);
	}

	public java.lang.String getYxq() {
		return get("YXQ");
	}

	public void setYwlxr(java.lang.String ywlxr) {
		set("YWLXR", ywlxr);
	}

	public java.lang.String getYwlxr() {
		return get("YWLXR");
	}

	public void setLxrsj(java.lang.String lxrsj) {
		set("LXRSJ", lxrsj);
	}

	public java.lang.String getLxrsj() {
		return get("LXRSJ");
	}

	public void setBgcz(java.lang.String bgcz) {
		set("BGCZ", bgcz);
	}

	public java.lang.String getBgcz() {
		return get("BGCZ");
	}

	public void setBgdh(java.lang.String bgdh) {
		set("BGDH", bgdh);
	}

	public java.lang.String getBgdh() {
		return get("BGDH");
	}

	public void setLxryx(java.lang.String lxryx) {
		set("LXRYX", lxryx);
	}

	public java.lang.String getLxryx() {
		return get("LXRYX");
	}

	public void setLxrzw(java.lang.String lxrzw) {
		set("LXRZW", lxrzw);
	}

	public java.lang.String getLxrzw() {
		return get("LXRZW");
	}

	public void setBgdz(java.lang.String bgdz) {
		set("BGDZ", bgdz);
	}

	public java.lang.String getBgdz() {
		return get("BGDZ");
	}

	public void setZzzs(java.lang.String zzzs) {
		set("ZZZS", zzzs);
	}

	public java.lang.String getZzzs() {
		return get("ZZZS");
	}

	public void setBlgyscfzq(java.lang.String blgyscfzq) {
		set("BLGYSCFZQ", blgyscfzq);
	}

	public java.lang.String getBlgyscfzq() {
		return get("BLGYSCFZQ");
	}

	public void setHmd(java.lang.String hmd) {
		set("HMD", hmd);
	}

	public java.lang.String getHmd() {
		return get("HMD");
	}

	public void setBlgysxypjdj(java.lang.String blgysxypjdj) {
		set("BLGYSXYPJDJ", blgysxypjdj);
	}

	public java.lang.String getBlgysxypjdj() {
		return get("BLGYSXYPJDJ");
	}

	public void setGysjyfw(java.lang.String gysjyfw) {
		set("GYSJYFW", gysjyfw);
	}

	public java.lang.String getGysjyfw() {
		return get("GYSJYFW");
	}

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("ENTRY_TIME", entryTime);
	}

	public java.util.Date getEntryTime() {
		return get("ENTRY_TIME");
	}

	public void setCertificateId(java.lang.String certificateId) {
		set("CERTIFICATE_ID", certificateId);
	}

	public java.lang.String getCertificateId() {
		return get("CERTIFICATE_ID");
	}

	public void setGysfl(java.lang.String gysfl) {
		set("GYSFL", gysfl);
	}

	public java.lang.String getGysfl() {
		return get("GYSFL");
	}

	public void setGysqyxz(java.lang.String gysqyxz) {
		set("GYSQYXZ", gysqyxz);
	}

	public java.lang.String getGysqyxz() {
		return get("GYSQYXZ");
	}

	public void setYyzzzp(java.lang.String yyzzzp) {
		set("YYZZZP", yyzzzp);
	}

	public java.lang.String getYyzzzp() {
		return get("YYZZZP");
	}

}
