package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuppliestemplate<M extends BaseSuppliestemplate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setLb(java.lang.String lb) {
		set("LB", lb);
	}

	public java.lang.String getLb() {
		return get("LB");
	}

	public void setWzbm(java.lang.String wzbm) {
		set("WZBM", wzbm);
	}

	public java.lang.String getWzbm() {
		return get("WZBM");
	}

	public void setWzmc(java.lang.String wzmc) {
		set("WZMC", wzmc);
	}

	public java.lang.String getWzmc() {
		return get("WZMC");
	}

	public void setGgxh(java.lang.String ggxh) {
		set("GGXH", ggxh);
	}

	public java.lang.String getGgxh() {
		return get("GGXH");
	}

	public void setJldw(java.lang.String jldw) {
		set("JLDW", jldw);
	}

	public java.lang.String getJldw() {
		return get("JLDW");
	}

	public void setSwtp(java.lang.String swtp) {
		set("SWTP", swtp);
	}

	public java.lang.String getSwtp() {
		return get("SWTP");
	}

	public void setBz(java.lang.String bz) {
		set("BZ", bz);
	}

	public java.lang.String getBz() {
		return get("BZ");
	}

	public void setSwtp2(java.lang.String swtp2) {
		set("SWTP2", swtp2);
	}

	public java.lang.String getSwtp2() {
		return get("SWTP2");
	}

	public void setSwtp3(java.lang.String swtp3) {
		set("SWTP3", swtp3);
	}

	public java.lang.String getSwtp3() {
		return get("SWTP3");
	}

	public void setQymc2(java.lang.String qymc2) {
		set("QYMC2", qymc2);
	}

	public java.lang.String getQymc2() {
		return get("QYMC2");
	}

}
