package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCersort<M extends BaseCersort<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setCersortname(java.lang.String cersortname) {
		set("CERSORTNAME", cersortname);
	}

	public java.lang.String getCersortname() {
		return get("CERSORTNAME");
	}

}
