package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSuppliersort<M extends BaseSuppliersort<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setGyssortname(java.lang.String gyssortname) {
		set("GYSSORTNAME", gyssortname);
	}

	public java.lang.String getGyssortname() {
		return get("GYSSORTNAME");
	}

}
