package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setNo(java.lang.String no) {
		set("NO", no);
	}

	public java.lang.String getNo() {
		return get("NO");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("ENTRY_TIME", entryTime);
	}

	public java.util.Date getEntryTime() {
		return get("ENTRY_TIME");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("CREATER_ID", createrId);
	}

	public java.lang.String getCreaterId() {
		return get("CREATER_ID");
	}

	public void setType(java.math.BigDecimal type) {
		set("TYPE", type);
	}

	public java.math.BigDecimal getType() {
		return get("TYPE");
	}

}
