package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCertificate<M extends BaseCertificate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setNo(java.lang.String no) {
		set("NO", no);
	}

	public java.lang.String getNo() {
		return get("NO");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setContent(java.lang.String content) {
		set("CONTENT", content);
	}

	public java.lang.String getContent() {
		return get("CONTENT");
	}

	public void setStartTime(java.lang.String startTime) {
		set("START_TIME", startTime);
	}

	public java.lang.String getStartTime() {
		return get("START_TIME");
	}

	public void setEndTime(java.lang.String endTime) {
		set("END_TIME", endTime);
	}

	public java.lang.String getEndTime() {
		return get("END_TIME");
	}

	public void setUnit(java.lang.String unit) {
		set("UNIT", unit);
	}

	public java.lang.String getUnit() {
		return get("UNIT");
	}

	public void setSupplierId(java.lang.String supplierId) {
		set("SUPPLIER_ID", supplierId);
	}

	public java.lang.String getSupplierId() {
		return get("SUPPLIER_ID");
	}

	public void setZslb(java.lang.String zslb) {
		set("ZSLB", zslb);
	}

	public java.lang.String getZslb() {
		return get("ZSLB");
	}

	public void setZsxx(java.lang.String zsxx) {
		set("ZSXX", zsxx);
	}

	public java.lang.String getZsxx() {
		return get("ZSXX");
	}

	public void setZszp(java.lang.String zszp) {
		set("ZSZP", zszp);
	}

	public java.lang.String getZszp() {
		return get("ZSZP");
	}

	public void setZszp2(java.lang.String zszp2) {
		set("ZSZP2", zszp2);
	}

	public java.lang.String getZszp2() {
		return get("ZSZP2");
	}

	public void setZszp3(java.lang.String zszp3) {
		set("ZSZP3", zszp3);
	}

	public java.lang.String getZszp3() {
		return get("ZSZP3");
	}

	public void setZsshwz(java.lang.String zsshwz) {
		set("ZSSHWZ", zsshwz);
	}

	public java.lang.String getZsshwz() {
		return get("ZSSHWZ");
	}

}
