package com.sinorail.gysglbj.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuote<M extends BaseQuote<M>> extends Model<M> implements IBean {

	public void setBjh(java.math.BigDecimal bjh) {
		set("BJH", bjh);
	}

	public java.math.BigDecimal getBjh() {
		return get("BJH");
	}

	public void setWzbm(java.lang.String wzbm) {
		set("WZBM", wzbm);
	}

	public java.lang.String getWzbm() {
		return get("WZBM");
	}

	public void setWzmc(java.lang.String wzmc) {
		set("WZMC", wzmc);
	}

	public java.lang.String getWzmc() {
		return get("WZMC");
	}

	public void setGgxh(java.lang.String ggxh) {
		set("GGXH", ggxh);
	}

	public java.lang.String getGgxh() {
		return get("GGXH");
	}

	public void setJsyq(java.lang.String jsyq) {
		set("JSYQ", jsyq);
	}

	public java.lang.String getJsyq() {
		return get("JSYQ");
	}

	public void setJldw(java.lang.String jldw) {
		set("JLDW", jldw);
	}

	public java.lang.String getJldw() {
		return get("JLDW");
	}

	public void setYcsl(java.lang.String ycsl) {
		set("YCSL", ycsl);
	}

	public java.lang.String getYcsl() {
		return get("YCSL");
	}

	public void setDjxjBhs(java.math.BigDecimal djxjBhs) {
		set("DJXJ_BHS", djxjBhs);
	}

	public java.math.BigDecimal getDjxjBhs() {
		return get("DJXJ_BHS");
	}

	public void setZxjBhs(java.math.BigDecimal zxjBhs) {
		set("ZXJ_BHS", zxjBhs);
	}

	public java.math.BigDecimal getZxjBhs() {
		return get("ZXJ_BHS");
	}

	public void setSydwjdq(java.lang.String sydwjdq) {
		set("SYDWJDQ", sydwjdq);
	}

	public java.lang.String getSydwjdq() {
		return get("SYDWJDQ");
	}

	public void setCsbdjBhs(java.math.BigDecimal csbdjBhs) {
		set("CSBDJ_BHS", csbdjBhs);
	}

	public java.math.BigDecimal getCsbdjBhs() {
		return get("CSBDJ_BHS");
	}

	public void setCsbzxjBhs(java.math.BigDecimal csbzxjBhs) {
		set("CSBZXJ_BHS", csbzxjBhs);
	}

	public java.math.BigDecimal getCsbzxjBhs() {
		return get("CSBZXJ_BHS");
	}

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("ENTRY_TIME", entryTime);
	}

	public java.util.Date getEntryTime() {
		return get("ENTRY_TIME");
	}

	public void setSupplierId(java.lang.String supplierId) {
		set("SUPPLIER_ID", supplierId);
	}

	public java.lang.String getSupplierId() {
		return get("SUPPLIER_ID");
	}

	public void setProjectId(java.lang.String projectId) {
		set("PROJECT_ID", projectId);
	}

	public java.lang.String getProjectId() {
		return get("PROJECT_ID");
	}

	public void setSfyxbj(java.lang.String sfyxbj) {
		set("SFYXBJ", sfyxbj);
	}

	public java.lang.String getSfyxbj() {
		return get("SFYXBJ");
	}

}
