package com.sinorail.gysglbj.model;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.sinorail.gysglbj.model.base.BaseCersort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cersort extends BaseCersort<Cersort> {
	public static final Cersort dao = new Cersort().dao();

	
	
	/**
	 * 
	 * 分页方法
	 * @param pageNumber
	 * @param pageSize
	 * @param model
	 * @return
	 */
	public Page<Cersort> findPaginate(Integer pageNumber, Integer pageSize, Cersort cersort) {
		
		Kv kv = Kv.by("CERSORTNAME", cersort.getCersortname());
		SqlPara sqlPara = getSqlPara("cersort.cersortList",kv);
		
		return paginate(pageNumber, pageSize, sqlPara);
		
	}


	/**
	 * 
	 * 根据证书的类别查找类别是否存在
	 * @param cersortname
	 * @return
	 */
	public boolean isExistSortname(String cersortname) {
		
			Cersort cersort = findFirst(getSql("cersort.findBySortName"),cersortname); 
			if(cersort == null){
				return false;
			}
			return true;
		}

	public boolean isExistSortname(String cersortname, String id) {
		
		Cersort cersort = findFirst(getSql("cersort.findBysortNameAndId"),cersortname,id); 
		if(cersort == null){
			return false;
		}
		return true;
	}

	public Object queryById(String para) {
		
		return findById(para);
	}


	public boolean deleteByIds(String ids) {
		
		boolean flag = true;
		try {
			String[] idArr = ids.split(",");
			for (String id : idArr) {
					deleteById(id);
			}
		} catch (Exception e) {
			flag = false;
		}
		return flag;
	}
	
	
}
