package com.sinorail.gysglbj.model;

import java.util.List;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.activerecord.SqlPara;
import com.sinorail.gysglbj.model.base.BaseCersuppliestemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cersuppliestemplate extends BaseCersuppliestemplate<Cersuppliestemplate> {
	public static final Cersuppliestemplate dao = new Cersuppliestemplate().dao();
	
	/**
	 * 
	 * 分页方法
	 * @param pageNumber
	 * @param pageSize
	 * @param model
	 * @return
	 */
	public Page<Cersuppliestemplate> findPaginate(Integer pageNumber, Integer pageSize, Cersuppliestemplate suppliestemplate) { 
		
		Kv kv = Kv.by("WZBM", suppliestemplate.getWzbm()).set("WZMC", suppliestemplate.getWzmc()).set("QYMC2",suppliestemplate.getQymc2()).set("ZSLB2",suppliestemplate.getZslb2()); 
		
		SqlPara sqlPara = getSqlPara("cersuppliestemplate.suppliestemplateList",kv);
		
		return paginate(pageNumber, pageSize, sqlPara);
		
	}


	/**
	 * 
	 * 根据证书的类别查找类别是否存在
	 * @param suppliestemplatename
	 * @return
	 */
	public boolean isExistSupplierCode(String suppliestemplatename) {
		
			Cersuppliestemplate suppliestemplate = findFirst(getSql("cersuppliestemplate.findByWzbm"),suppliestemplatename); 
			if(suppliestemplate == null){
				return false;
			}
			return true;
		}

	public boolean findByWzbmAndId(String suppliestemplatename, String id) {
		
		Cersuppliestemplate suppliestemplate = findFirst(getSql("cersuppliestemplate.findByWzbmAndId"),suppliestemplatename,id); 
		if(suppliestemplate == null){
			return false;
		}
		return true;
	}

	public Object queryById(String para) {
		
		return findById(para);
	}


	public boolean deleteByIds(String ids) {
		
		boolean flag = true;
		try {
			String[] idArr = ids.split(",");
			for (String id : idArr) {
					deleteById(id);
			}
		} catch (Exception e) {
			flag = false;
		}
		return flag;
	}
	
	public List<Cersuppliestemplate> findWzbm() {
		String sql  = "select WZBM from  E_CERSUPPLIESTEMPLATE";
		return find(sql);  
	}


	public List<Record> findExportWzk(Cersuppliestemplate suppliestemplate) {
		
		Kv cond = Kv.by("WZBM",suppliestemplate.getWzbm()).set("WZMC", suppliestemplate.getWzmc()).set("QYMC2", suppliestemplate.getQymc2()).set("ZSLB2", suppliestemplate.getZslb2());  
		SqlPara sqlp = getSqlPara("cersuppliestemplate.suppliestemplateList",cond);
		
		return Db.find(sqlp);
	}


	public void updateSWTP(String id) {
		String sql  = "update E_CERSUPPLIESTEMPLATE set SWTP=A"+" where ID="+id;
		//String sql  = "update E_SUPPLIESTEMPLATE set SWTP=A"+", SWTP2=?"+", SWTP3=?"+" where ID="+id;
		Db.update(sql);
	}
}
