package com.sinorail.gysglbj.model;

import com.sinorail.gysglbj.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	public static final Project dao = new Project().dao();
}
