package com.sinorail.gysglbj.model;

import java.util.List;

import com.sinorail.gysglbj.model.base.BaseQuote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Quote extends BaseQuote<Quote> {
	public static final Quote dao = new Quote().dao();
	
	
	/**
	 * 
	 * 根据供应商id查询报价表
	 */
	public List<Quote> queryByCerId(String cerId){
		
		String sql = "select * from E_QUOTE where SUPPLIER_ID = ?";
		return find(sql, cerId);
	}
}
