package com.sinorail.gysglbj.model;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.sinorail.gysglbj.model.base.BaseSuppliersort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suppliersort extends BaseSuppliersort<Suppliersort> {
	
	public static final Suppliersort dao = new Suppliersort().dao();
	
	
	
	/**
	 * 
	 * 分页方法
	 * @param pageNumber
	 * @param pageSize
	 * @param model
	 * @return
	 */
	public Page<Suppliersort> findPaginate(Integer pageNumber, Integer pageSize, Suppliersort suppliersort) {
		
		Kv kv = Kv.by("GYSSORTNAME", suppliersort.getGyssortname());
		
		SqlPara sqlPara = getSqlPara("suppliersort.suppliersortList",kv);
		
		return paginate(pageNumber, pageSize, sqlPara);
		
	}


	/**
	 * 
	 * 根据证书的类别查找类别是否存在
	 * @param suppliersortname
	 * @return
	 */
	public boolean isExistGysSortname(String suppliersortname) {
		
			Suppliersort suppliersort = findFirst(getSql("suppliersort.findByGysSortName"),suppliersortname); 
			if(suppliersort == null){
				return false;
			}
			return true;
		}

	public boolean isExistGysSortname(String suppliersortname, String id) {
		
		Suppliersort suppliersort = findFirst(getSql("suppliersort.findByGysSortNameAndId"),suppliersortname,id); 
		if(suppliersort == null){
			return false;
		}
		return true;
	}

	public Object queryById(String para) {
		
		return findById(para);
	}


	public boolean deleteByIds(String ids) {
		
		boolean flag = true;
		try {
			String[] idArr = ids.split(",");
			for (String id : idArr) {
					deleteById(id);
			}
		} catch (Exception e) {
			flag = false;
		}
		return flag;
	}
}
