package com.sinorail.gysglbj.model;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.sinorail.gysglbj.model.base.BaseSuppliergrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suppliergrade extends BaseSuppliergrade<Suppliergrade> {
	
	
	public static final Suppliergrade dao = new Suppliergrade().dao();
	
	
	/**
	 * 
	 * 分页方法
	 * @param pageNumber
	 * @param pageSize
	 * @param model
	 * @return
	 */
	public Page<Suppliergrade> findPaginate(Integer pageNumber, Integer pageSize, Suppliergrade Suppliergrade) {
		
		Kv kv = Kv.by("GRADEPJ", Suppliergrade.getGradepj());
		
		SqlPara sqlPara = getSqlPara("suppliergrade.suppliergradeList",kv);
		
		return paginate(pageNumber, pageSize, sqlPara);
		
	}


	/**
	 * 
	 * 根据证书的类别查找类别是否存在
	 * @param GRADEPJ
	 * @return
	 */
	public boolean isExistgradename(String GRADEPJ) {
		
			Suppliergrade Suppliergrade = findFirst(getSql("suppliergrade.findByGradepj"),GRADEPJ); 
			if(Suppliergrade == null){
				return false;
			}
			return true;
		}

	public boolean isExistgradename(String GRADEPJ, String id) {
		
		Suppliergrade Suppliergrade = findFirst(getSql("suppliergrade.findByGradepjAndId"),GRADEPJ,id); 
		if(Suppliergrade == null){
			return false;
		}
		return true;
	}

	public Object queryById(String para) {
		
		return findById(para);
	}


	public boolean deleteByIds(String ids) {
		
		boolean flag = true;
		try {
			String[] idArr = ids.split(",");
			for (String id : idArr) {
					deleteById(id);
			}
		} catch (Exception e) {
			flag = false;
		}
		return flag;
	}
}

